//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DulsaWeb.Modelo
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Clientes")]
    public partial class Cliente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Regimen { get; set; }
        public string Nacionalidad { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Lugarnacimiento { get; set; }
        public string Telefonocasa { get; set; }
        public string TelefonoCelular { get; set; }
        public string TelefonoOficina { get; set; }
        public string Email { get; set; }
        public string Empresa { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public string Beneficiario { get; set; }
    }
}
