//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ListaVentas")]
    public partial class ListaVenta
    {
        public int Id { get; set; }
        public int PrototipoId { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string Estatus { get; set; }
    
        public virtual Prototipo Prototipo { get; set; }
    }
}
