//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Lotes")]
    public partial class Lote
    {
        public int Id { get; set; }
        public Nullable<int> Descripcion { get; set; }
        public Nullable<int> Manzana { get; set; }
        public Nullable<int> Etapa { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public Nullable<decimal> M2Excedente { get; set; }
        public Nullable<decimal> ImporteExcedente { get; set; }
        public Nullable<decimal> Esquina { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string Estatus { get; set; }
    }
}
