//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int id_cliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Regimen { get; set; }
        public string Nacionalidad { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Lugar_nacimiento { get; set; }
        public Nullable<decimal> Telefono_casa { get; set; }
        public Nullable<decimal> Telefono_Celular { get; set; }
        public Nullable<decimal> Telefono_Oficina { get; set; }
        public string Email { get; set; }
        public string Empresa { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public string Beneficiario { get; set; }
    }
}
