//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_Venta
    {
        public int id_lista { get; set; }
        public int id_prototipo { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public string Estatus { get; set; }
    
        public virtual prototipos prototipos { get; set; }
    }
}
