//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lotes
    {
        public int id_lote { get; set; }
        [Required]
        public Nullable<int> Lote { get; set; }
        public Nullable<int> Manzana { get; set; }
        public Nullable<int> Etapa { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public Nullable<decimal> M2_Excedente { get; set; }
        public Nullable<decimal> Importe_Excedente { get; set; }
        public Nullable<decimal> Esquina { get; set; }
        public Nullable<decimal> Importe_Total { get; set; }
        public string Estatus { get; set; }
    }
}
