//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DulsaWebEntities : DbContext
    {
        public DulsaWebEntities()
            : base("name=DulsaWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lotes> Lotes { get; set; }
        public virtual DbSet<Asesores> Asesores { get; set; }
        public virtual DbSet<Lista_Venta> Lista_Venta { get; set; }
        public virtual DbSet<prototipos> prototipos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
    }
}
