//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prototipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prototipos()
        {
            this.Lista_Venta = new HashSet<Lista_Venta>();
        }
    
        public int id_prototipo { get; set; }
        public string Prototipo { get; set; }
        public Nullable<decimal> M2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lista_Venta> Lista_Venta { get; set; }
    }
}
